<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Chiranjeevi-PC" failures="2" tests="9" name="com.infosys.opencart.tests.LoginTestDDT" time="74.814" errors="0" timestamp="2025-08-07T20:15:40 IST" skipped="0">
  <testcase classname="com.infosys.opencart.tests.LoginTestDDT" name="verify_login_test" time="11.802">
    <failure message="Expected login to succeed but it failed for valid user: lespinal1@360.cn" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected login to succeed but it failed for valid user: lespinal1@360.cn
at org.testng.Assert.fail(Assert.java:111)
at com.infosys.opencart.tests.LoginTestDDT.verify_login_test(LoginTestDDT.java:66)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verify_login_test -->
  <testcase classname="com.infosys.opencart.tests.LoginTestDDT" name="verify_login_test" time="11.070"/>
  <testcase classname="com.infosys.opencart.tests.LoginTestDDT" name="verify_login_test" time="2.065">
    <failure message="Expected login to fail but it succeeded for invalid user: abc123@gmail.com" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected login to fail but it succeeded for invalid user: abc123@gmail.com
at org.testng.Assert.fail(Assert.java:111)
at com.infosys.opencart.tests.LoginTestDDT.verify_login_test(LoginTestDDT.java:73)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verify_login_test -->
  <testcase classname="com.infosys.opencart.tests.LoginTestDDT" name="verify_login_test" time="10.956"/>
  <testcase classname="com.infosys.opencart.tests.LoginTestDDT" name="verify_login_test" time="10.879"/>
  <testcase classname="com.infosys.opencart.tests.LoginTestDDT" name="verify_login_test" time="11.731"/>
  <testcase classname="com.infosys.opencart.tests.LoginTestDDT" name="verify_login_test" time="3.245"/>
  <testcase classname="com.infosys.opencart.tests.LoginTestDDT" name="verify_login_test" time="2.080"/>
  <testcase classname="com.infosys.opencart.tests.LoginTestDDT" name="verify_login_test" time="10.986"/>
</testsuite> <!-- com.infosys.opencart.tests.LoginTestDDT -->
